#!/usr/bin/env python3
import sys
import os
import json


def get_pkgs():
    cybersec_path = os.environ["PATH_CYBERSEC"] + "/"
    pkgs = []
    with open(cybersec_path + "pkgs.nix", "r") as f:
        for line in f:
            if "#" not in line and line != "\n":
                pkgs.append(line.split()[0])
    pkgs = pkgs[3:-2]
    return pkgs


if len(sys.argv) > 1:
    query = " ".join(sys.argv[1:])
    if sys.argv[1] == "-h" or sys.argv[1] == "--help":
        print("Usage: tools [query]")
        print("List all available tools or search for a specific tool")
        exit(0)
    else:
        pkgs = get_pkgs()
        print("Searching for \033[0;32m" + query + "\033[0m...")
        for pkg in pkgs:
            if query in pkg:
                print(pkg)
else:
    print("Available tools:")
    pkgs = get_pkgs()
    for pkg in pkgs:
        print(pkg)

# #!/usr/bin/env bash
# 	if [ "$1" == "-h" ] || [ "$2" == "--help" ]; then
# 		echo -e "Usage: tools [query]"
# 		echo -e "List all available tools or search for a specific tool"
# 		exit 0
# 	fi
# 	if [ -z "$1" ]; then
# 		echo -e "Available tools:"
# 		cat $PATH_CYBERSEC/pkgs.nix | head -n -2 | tail -n +4 | sed 's/ //g'
# 	else
# 		echo -e "Searching for \033[0;32m$1\033[0m..."
# 		cat $PATH_CYBERSEC/pkgs.nix | head -n -2 | tail -n +4 | sed 's/ //g' | grep -v "#" | grep --color=auto "$1"
# 	fi
#
# 	python3 $PATH_CYBERSEC/tools/search.py
#
